pub struct AnalyzeHumanOutputInput<'a> {
    pub structure_bias: &'a str,
    pub latest_break: Option<&'a str>,
    pub liquidity_sweeps_recent: usize,
    pub open_fvgs: usize,
    pub price_action_narrative: &'a str,
    pub last_closed_bar_close: f64,
    pub ema20: Option<f64>,
    pub ema50: Option<f64>,
    pub rsi14: Option<f64>,
    pub adx14: Option<f64>,
    pub technical_narrative: &'a str,
    pub paired_market_available: bool,
    pub rolling_correlation_20: Option<f64>,
    pub rolling_correlation_50: Option<f64>,
    pub divergence_detected: Option<bool>,
    pub smt_narrative: &'a str,
    pub hmm_state: &'a str,
    pub regime_label: &'a str,
    pub bull_probability: f64,
    pub bear_probability: f64,
    pub selected_direction: &'a str,
    pub actionable: bool,
    pub trade_direction: &'a str,
    pub entry: f64,
    pub stop_loss: f64,
    pub take_profits: &'a [f64],
    pub risk_reward: f64,
    pub trade_plan_narrative: &'a str,
}

pub fn build_human_output(input: &AnalyzeHumanOutputInput<'_>) -> String {
    format!(
        "第一个代码块：基本价格结构分析\n- 结构偏向：{}\n- 最新破坏：{:?}\n- 近期流动性清扫：{}\n- 未回补FVG：{}\n- 说明：{}\n\n第二个代码块：技术面价格分析\n- 收盘价：{:.2}\n- EMA20：{:?}\n- EMA50：{:?}\n- RSI14：{:?}\n- ADX14：{:?}\n- 说明：{}\n\n第三个代码块：SMT相关性分析\n- 配对市场可用：{}\n- 20期相关：{:?}\n- 50期相关：{:?}\n- 是否背离：{:?}\n- 说明：{}\n\n第四个代码块：regime分类结合贝叶斯分析并给推测概率\n- HMM状态：{}\n- regime：{}\n- bull概率：{:.3}\n- bear概率：{:.3}\n- 当前方向：{}\n\n第五个代码块：给用户交易计划，你应该在什么地方入场，做多还是做空，止损止盈怎么放\n- 是否可执行：{}\n- 方向：{}\n- 入场：{:.2}\n- 止损：{:.2}\n- 止盈：{:?}\n- 风险收益比：{:.2}\n- 说明：{}",
        input.structure_bias,
        input.latest_break,
        input.liquidity_sweeps_recent,
        input.open_fvgs,
        input.price_action_narrative,
        input.last_closed_bar_close,
        input.ema20,
        input.ema50,
        input.rsi14,
        input.adx14,
        input.technical_narrative,
        input.paired_market_available,
        input.rolling_correlation_20,
        input.rolling_correlation_50,
        input.divergence_detected,
        input.smt_narrative,
        input.hmm_state,
        input.regime_label,
        input.bull_probability,
        input.bear_probability,
        input.selected_direction,
        input.actionable,
        input.trade_direction,
        input.entry,
        input.stop_loss,
        input.take_profits,
        input.risk_reward,
        input.trade_plan_narrative,
    )
}
